/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caygiapha;

import java.awt.event.KeyEvent;
import java.util.Date;
import java.sql.*;
import java.util.logging.Level;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ADT
 */
public class ADD_KT extends javax.swing.JInternalFrame {
    
    private final String head[]={"STT","Họ và tên","Ngày sinh","Đời","Cha/mẹ"};
    
    private final DefaultTableModel tb= new DefaultTableModel(head,0);
    private String[] data;
    /**
     * Creates new form ADD_KT_1
     */
    Date date = new Date();
    DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
    Calendar cal= Calendar.getInstance();
    DefaultTableModel model;
    boolean edit=true;
    public ADD_KT() {
        initComponents();
        hovaten.setEditable(false);
        ngaysinh.setEditable(false);
        timtc.setVisible(false);
        them.setEnabled(false);
        baoloi.setVisible(false);
        Date n=new Date();
        setVisible(true);
    }

    public ADD_KT(String ma){
        initComponents();
        hovaten.setEditable(false);
        ngaysinh.setEditable(false);
        timtc.setVisible(false);
        baoloi.setVisible(false);
        Date n=new Date();
        matv.setText(ma);
        matv.setEditable(false);
        Search_KT(matv.getText());
        tim.setEnabled(false);
        setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        baoloi = new javax.swing.JDialog();
        dongloi = new javax.swing.JButton();
        textloi = new javax.swing.JLabel();
        L_ngaysinh = new javax.swing.JLabel();
        L_ngaymat = new javax.swing.JLabel();
        L_hovaten = new javax.swing.JLabel();
        hovaten = new javax.swing.JTextField();
        thangmat = new javax.swing.JComboBox<>();
        ngaymat = new javax.swing.JComboBox<>();
        nammat = new javax.swing.JTextField();
        L_mathanhvien = new javax.swing.JLabel();
        matv = new javax.swing.JTextField();
        tua = new javax.swing.JLabel();
        them = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dong = new javax.swing.JButton();
        ngaysinh = new javax.swing.JTextField();
        tim = new javax.swing.JButton();
        timtc = new javax.swing.JLabel();
        diadiemmaitang = new javax.swing.JComboBox<>();
        nguyennhanmat = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        baoloi.setTitle("không tìm thấy");
        baoloi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        baoloi.setLocation(new java.awt.Point(600, 350));
        baoloi.setMinimumSize(new java.awt.Dimension(290, 150));
        baoloi.setSize(getMinimumSize());
        baoloi.setType(java.awt.Window.Type.POPUP);

        dongloi.setText("Đóng");
        dongloi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dongloiActionPerformed(evt);
            }
        });

        textloi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textloi.setText("Không tìm thấy thành viên");

        javax.swing.GroupLayout baoloiLayout = new javax.swing.GroupLayout(baoloi.getContentPane());
        baoloi.getContentPane().setLayout(baoloiLayout);
        baoloiLayout.setHorizontalGroup(
            baoloiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baoloiLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(dongloi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(baoloiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textloi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        baoloiLayout.setVerticalGroup(
            baoloiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baoloiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textloi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(dongloi)
                .addContainerGap())
        );

        setClosable(true);
        setTitle("Ghi Nhận Khai Tử");

        L_ngaysinh.setText("Ngày sinh:");

        L_ngaymat.setText("Ngày mất:");

        L_hovaten.setText("Họ và Tên:");

        hovaten.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                hovatenKeyPressed(evt);
            }
        });

        thangmat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        thangmat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thangmatActionPerformed(evt);
            }
        });

        ngaymat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        L_mathanhvien.setText("Mã thành viên:");

        matv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matvActionPerformed(evt);
            }
        });
        matv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                matvKeyPressed(evt);
            }
        });

        tua.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tua.setText("THÊM GIẤY KHAI TỬ");

        them.setText("Thêm");
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });

        jLabel6.setText("Địa điểm mai táng:");

        jLabel7.setText("Nguyên nhân mất:");

        dong.setText("Đóng");
        dong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dongActionPerformed(evt);
            }
        });

        tim.setText("Tìm");
        tim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timMouseClicked(evt);
            }
        });
        tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timActionPerformed(evt);
            }
        });

        timtc.setText("ĐÃ TÌM THẤY THÀNH VIÊN");

        diadiemmaitang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Hà Nội", "Đà Nẵng", "Tp Hồ Chí Minh" }));

        nguyennhanmat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Bệnh Lao", "Ung Thư", "Chấn Thương Sọ Não", "Tai Nạn Xe Cộ", "Bệnh Gan", "Bệnh Phổi", "Đột Quỵ", "Bệnh Tim", "Kháng Chiến", "Bệnh HIV", "Bệnh Sốt Xuất Huyết", "Bệnh H5N1", " " }));

        jLabel1.setText("Năm");

        jLabel2.setText("Tháng");

        jLabel3.setText("Ngày");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(them, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dong, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(L_ngaymat))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ngaymat, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(thangmat, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nammat, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(diadiemmaitang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(nguyennhanmat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(L_mathanhvien)
                                .addGap(35, 35, 35)
                                .addComponent(matv, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_hovaten)
                            .addComponent(L_ngaysinh))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hovaten)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)
                                .addComponent(tim, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 10, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(timtc)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tua, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L_mathanhvien)
                            .addComponent(matv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L_hovaten)
                            .addComponent(hovaten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_ngaysinh)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tim)))
                        .addGap(14, 14, 14)
                        .addComponent(timtc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ngaymat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thangmat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nammat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_ngaymat)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addComponent(diadiemmaitang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(nguyennhanmat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(them)
                    .addComponent(dong))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void thangmatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thangmatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thangmatActionPerformed

    private void dongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dongActionPerformed
        // TODO add your handling code here:
        this.dispose();
        //MAIN.a.getJDesktop().add(new XTV());
    }//GEN-LAST:event_dongActionPerformed

    private void hovatenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hovatenKeyPressed


        // TODO add your handling code here:
    }//GEN-LAST:event_hovatenKeyPressed

    private void matvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matvActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_matvActionPerformed

    private void timMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_timMouseClicked


    
    private void Search_KT(String ma){
        try {
            String SQL1="select HVT,NS from TV where id like '"+ma+"'";
            String SQL2="select * from KT where ID like '"+ma+"'";
            Statement sta=SQL.getConnection().createStatement();
            ResultSet r1=sta.executeQuery(SQL1);
            if(r1.isBeforeFirst()){
                r1.next();
                hovaten.setText(r1.getString("HVT"));
                ngaysinh.setText(r1.getString("NS"));
                timtc.setText("ĐÃ TÌM THẤY THÀNH VIÊN");
                r1=sta.executeQuery(SQL2);
                if(r1.isBeforeFirst()){
                    timtc.setText("Thành viên này đã có giấy khai tử.");
                    them.setEnabled(false);
                } else {
                    them.setEnabled(true);
                }
            } else {
                timtc.setText("Không tìm thấy thành viên này.");
                them.setEnabled(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ADD_KT.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timActionPerformed
        // TODO add your handling code here:
        Search_KT(matv.getText());

    }//GEN-LAST:event_timActionPerformed

    private void themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themActionPerformed
        Statement a=null;
        ResultSet r;
        String idtv=matv.getText();
        
        String nc = new String((String)ngaymat.getSelectedItem()+"/"+(String)thangmat.getSelectedItem()+"/"+nammat.getText());
        
        String ngnh= (String) nguyennhanmat.getSelectedItem();
        String nmt= (String) diadiemmaitang.getSelectedItem();
        Date nm= new Date(Integer.valueOf(nammat.getText())-1900,thangmat.getSelectedIndex(),ngaymat.getSelectedIndex()+1);
        
        Date n = new Date();
        Date ns = null;
        try{
        String S="select ns from tv where id like '"+matv.getText()+"'";
        a=SQL.getConnection().createStatement();
        r=a.executeQuery(S);
        r.next();
        ns = r.getDate(1);
        }
        catch (SQLException ex) {
            Logger.getLogger(ADD_KT.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
        
        if(nm.after(n)||nm.before(ns)){
            textloi.setText("Lỗi nhập sai ngày");
            baoloi.setVisible(true);
            return;
        }
            
        
        
        String sql="insert into KT values ('"+idtv+"','"+nc+"',N'"+ngnh+"',N'"+nmt+"')";
        try {
            a=SQL.getConnection().createStatement();
            a.executeUpdate(sql);
            timtc.setText("THÊM THÀNH CÔNG");
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(ADD_KT.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_themActionPerformed

    private void matvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matvKeyPressed
        // TODO add your handling code here:
        if(!edit)
            return;
        char chr=evt.getKeyChar();
        
        if(chr==65535 || chr==KeyEvent.VK_DELETE || chr==KeyEvent.VK_BACK_SPACE){
            return;
        }
        
        if(chr==KeyEvent.VK_ENTER){
            Search_KT(matv.getText());
            return;
        }
        
        String id= matv.getText();
        int len=id.length();
        if(len==6 || len==7){
            Search_KT(matv.getText()+evt.getKeyChar());
        }
    }//GEN-LAST:event_matvKeyPressed

    private void dongloiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dongloiActionPerformed
        textloi.setText("Không tìm thấy thành viên");
        baoloi.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_dongloiActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_hovaten;
    private javax.swing.JLabel L_mathanhvien;
    private javax.swing.JLabel L_ngaymat;
    private javax.swing.JLabel L_ngaysinh;
    private javax.swing.JDialog baoloi;
    private javax.swing.JComboBox<String> diadiemmaitang;
    private javax.swing.JButton dong;
    private javax.swing.JButton dongloi;
    private javax.swing.JTextField hovaten;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField matv;
    private javax.swing.JTextField nammat;
    private javax.swing.JComboBox<String> ngaymat;
    private javax.swing.JTextField ngaysinh;
    private javax.swing.JComboBox<String> nguyennhanmat;
    private javax.swing.JLabel textloi;
    private javax.swing.JComboBox<String> thangmat;
    private javax.swing.JButton them;
    private javax.swing.JButton tim;
    private javax.swing.JLabel timtc;
    private javax.swing.JLabel tua;
    // End of variables declaration//GEN-END:variables
}