/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caygiapha;

import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ADT
 */
public class ADD_KT extends javax.swing.JInternalFrame {
    private final String head[]={"STT","Họ và tên","Ngày sinh","Đời","Cha/mẹ"};
    private final DefaultTableModel tb= new DefaultTableModel(head,0);
    private String[] data;
    /**
     * Creates new form ADD_KT_1
     */
    public ADD_KT() {
        initComponents();
        setVisible(true);
        hovaten.disable();
        ngaysinh.disable();
        loi.setVisible(false);
        timtc.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L_ngaysinh = new javax.swing.JLabel();
        L_ngaymat = new javax.swing.JLabel();
        L_hovaten = new javax.swing.JLabel();
        hovaten = new javax.swing.JTextField();
        thangmat = new javax.swing.JComboBox<>();
        ngaymat = new javax.swing.JComboBox<>();
        nammat = new javax.swing.JTextField();
        L_mathanhvien = new javax.swing.JLabel();
        matv = new javax.swing.JTextField();
        tua = new javax.swing.JLabel();
        them = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        diadiemmaitang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nguyennhanmat = new javax.swing.JTextField();
        dong = new javax.swing.JButton();
        ngaysinh = new javax.swing.JTextField();
        tim = new javax.swing.JButton();
        loi = new javax.swing.JLabel();
        timtc = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Ghi Nhận Khai Tử");

        L_ngaysinh.setText("Ngày sinh:");

        L_ngaymat.setText("Ngày mất:");

        L_hovaten.setText("Họ và Tên:");

        hovaten.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                hovatenKeyPressed(evt);
            }
        });

        thangmat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        thangmat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thangmatActionPerformed(evt);
            }
        });

        ngaymat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        L_mathanhvien.setText("Mã thành viên:");

        matv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matvActionPerformed(evt);
            }
        });

        tua.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tua.setText("THÊM GIẤY KHAI TỬ");

        them.setText("Thêm");
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });

        jLabel6.setText("Địa điểm mai táng:");

        diadiemmaitang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diadiemmaitangActionPerformed(evt);
            }
        });

        jLabel7.setText("Nguyên nhân mất:");

        dong.setText("Đóng");
        dong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dongActionPerformed(evt);
            }
        });

        tim.setText("Tìm");
        tim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timMouseClicked(evt);
            }
        });
        tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timActionPerformed(evt);
            }
        });

        loi.setText("THÀNH VIÊN NÀY ĐÃ CÓ GIẤY KHAI TỬ");

        timtc.setText("ĐÃ TÌM THẤY THÀNH VIÊN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(them, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dong, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(nguyennhanmat))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(L_ngaymat))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(diadiemmaitang)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ngaymat, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                                        .addComponent(thangmat, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(87, 87, 87)
                                        .addComponent(nammat, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(107, 107, 107)
                                        .addComponent(matv, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(L_mathanhvien))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_hovaten)
                            .addComponent(L_ngaysinh))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hovaten)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)
                                .addComponent(tim, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(timtc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loi)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tua, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_mathanhvien)
                    .addComponent(matv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_hovaten)
                    .addComponent(hovaten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_ngaysinh)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tim)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loi)
                    .addComponent(timtc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ngaymat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thangmat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nammat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_ngaymat))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(diadiemmaitang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nguyennhanmat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(them)
                    .addComponent(dong))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void thangmatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thangmatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thangmatActionPerformed

    private void dongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dongActionPerformed
        // TODO add your handling code here:
        this.dispose();
        //MAIN.a.getJDesktop().add(new XTV());
    }//GEN-LAST:event_dongActionPerformed

    private void diadiemmaitangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diadiemmaitangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diadiemmaitangActionPerformed

    private void hovatenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hovatenKeyPressed

        
        // TODO add your handling code here:
    }//GEN-LAST:event_hovatenKeyPressed

    private void matvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matvActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_matvActionPerformed

    private void timMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_timMouseClicked

    private void timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timActionPerformed
        // TODO add your handling code here:
        Statement a;
        ResultSet r,r1;
        String SQL1="select hvt, ns, id from tv where id like '"+ matv.getText()+"'";
        String SQL2="select id from KT";
          try {
              a=SQL.getConnection().createStatement();
              r=a.executeQuery(SQL1);
              if(r.isBeforeFirst()==true){
                r.next();
                hovaten.setText(r.getString(1));
                ngaysinh.setText(r.getString(2));
                timtc.setVisible(true);
              }
              r1=a.executeQuery(SQL2);
              r1.next();
              if(matv.getText().compareTo(r1.getString(1))==0){
                  loi.setVisible(true);
                  ngaymat.disable();
                  thangmat.disable();
                  nammat.disable();
                  diadiemmaitang.disable();
                  nguyennhanmat.disable();
                  timtc.setVisible(false);
              }
              else{
                  loi.setVisible(false);
                  timtc.setVisible(true);
                  ngaymat.enable();
                  thangmat.enable();
                  nammat.enable();
                  diadiemmaitang.enable();
                  nguyennhanmat.enable();
                  
              }
              
          } catch (SQLException ex) {
              Logger.getLogger(ADD_KT.class.getName()).log(Level.SEVERE, null, ex);
          }
          
    }//GEN-LAST:event_timActionPerformed

    private void themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themActionPerformed
        Statement a=null;
        String idtv=matv.getText();
        String nc= ngaymat.getItemAt(ngaymat.getSelectedIndex())+"/"+thangmat.getItemAt(thangmat.getSelectedIndex())+"/"+nammat.getText();
        String ngnh=nguyennhanmat.getText();
        String nmt=diadiemmaitang.getText();
        String sql="insert into KT values ('"+idtv+"','"+nc+"',N'"+ngnh+"',N'"+nmt+"')";
        try {
            a=SQL.getConnection().createStatement();
            a.executeUpdate(sql);
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(ADD_KT.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_themActionPerformed

            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_hovaten;
    private javax.swing.JLabel L_mathanhvien;
    private javax.swing.JLabel L_ngaymat;
    private javax.swing.JLabel L_ngaysinh;
    private javax.swing.JTextField diadiemmaitang;
    private javax.swing.JButton dong;
    private javax.swing.JTextField hovaten;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel loi;
    private javax.swing.JTextField matv;
    private javax.swing.JTextField nammat;
    private javax.swing.JComboBox<String> ngaymat;
    private javax.swing.JTextField ngaysinh;
    private javax.swing.JTextField nguyennhanmat;
    private javax.swing.JComboBox<String> thangmat;
    private javax.swing.JButton them;
    private javax.swing.JButton tim;
    private javax.swing.JLabel timtc;
    private javax.swing.JLabel tua;
    // End of variables declaration//GEN-END:variables
}
