/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caygiapha;

import java.sql.*;

/**
 *
 * @author ADT
 */
public class SMT extends javax.swing.JInternalFrame {

    /**
     * Creates new form SMT
     */
    public SMT() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        L_nguyennhan = new javax.swing.JLabel();
        L_ddmaitang = new javax.swing.JLabel();
        L_MaTT = new javax.swing.JLabel();
        MaTV = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        C_ddmaitang = new javax.swing.JComboBox<>();
        C_nguyennhan = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setTitle("Sửa nguyên nhân và nơi mai táng");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bảng Thay Đổi Nguyên Nhân và Địa Điểm Mai Táng");

        L_nguyennhan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        L_nguyennhan.setText("Nguyên Nhân");

        L_ddmaitang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        L_ddmaitang.setText("Địa Điểm Mai Táng");

        L_MaTT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        L_MaTT.setText("Mã TV");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("OK");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        C_ddmaitang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        C_ddmaitang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                     ", "TP.Hồ Chí Minh", "TP.Đà Nẵng", "TP.Hà Nôi" }));
        C_ddmaitang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_ddmaitangActionPerformed(evt);
            }
        });

        C_nguyennhan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        C_nguyennhan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                 ", "Bệnh Lao", "Ung Thư", "Chấn Thương Sọ Não", "Tai Nạn Xe Cộ", "Bệnh Gan", "Bệnh Phổi", "Đột Quỵ", "Bệnh Tim", "Kháng Chiến", "Bệnh HIV", "Bệnh Sốt Xuất Huyết", "Bệnh H5N1", " " }));
        C_nguyennhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_nguyennhanActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("QUIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(L_nguyennhan, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(C_nguyennhan, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(L_ddmaitang))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(L_MaTT, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MaTV)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C_ddmaitang, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_MaTT, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaTV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(L_ddmaitang, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(C_ddmaitang, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(C_nguyennhan, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(L_nguyennhan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void C_ddmaitangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_ddmaitangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C_ddmaitangActionPerformed

    private void C_nguyennhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_nguyennhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C_nguyennhanActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        String sql = "update KT set NN = N'"+C_nguyennhan.getItemAt(C_nguyennhan.getSelectedIndex())+"'";
        String sql1= " from TV a where KT.ID like '"+MaTV.getText()+"'";
        String sql2 = "update KT set NMT = N'"+C_ddmaitang.getItemAt(C_ddmaitang.getSelectedIndex())+"'";
        String sql3 = " from TV a where KT.ID like '"+MaTV.getText()+"'";
        
        try {
        Statement sta=SQL.getConnection().createStatement();
        sta.executeUpdate(sql+sql1);
        sta.executeUpdate(sql2+sql3);
        jLabel2.setText("Sua thanh cong.");
        } catch (SQLException ex) {
 //           Logger.getLogger(SMT.class.getName()).log(Level.SEVERE, null, ex);
            jLabel2.setText("Sua That bai.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> C_ddmaitang;
    private javax.swing.JComboBox<String> C_nguyennhan;
    private javax.swing.JLabel L_MaTT;
    private javax.swing.JLabel L_ddmaitang;
    private javax.swing.JLabel L_nguyennhan;
    private javax.swing.JTextField MaTV;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
