/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caygiapha;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ADT
 */
public class TGTV extends javax.swing.JInternalFrame {
        String a[]=new String[]{"STT","Năm","Số lượng sinh","Số lượng kết hôn","Số lượng mất"};
        DefaultTableModel tb;
    /**
     * Creates new form TGTV_1
     */
    public TGTV() {
        initComponents();
        tb=(DefaultTableModel) TK.getModel();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tunam = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dennam = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TK = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Thống kê các sự kiện tăng giảm thành viên");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THỐNG KÊ TĂNG GIẢM THÀNH VIÊN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Từ Năm");

        tunam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tunamActionPerformed(evt);
            }
        });
        tunam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tunamKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Đến Năm");

        dennam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dennamKeyPressed(evt);
            }
        });

        TK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "", "", null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Năm", "Số lượng sinh", "Số lượng kết hôn", "Số lượng mất"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TK.setEditingColumn(0);
        TK.setEditingRow(0);
        jScrollPane1.setViewportView(TK);

        jButton1.setText("Tìm");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Đóng");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("^_^");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tunam, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dennam, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(194, 194, 194))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tunam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(dennam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tunamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tunamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tunamActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        int begin=0;
        int end=9999;
        if(!tunam.getText().isEmpty()){
            begin=Integer.valueOf(tunam.getText());
        }
        if(!dennam.getText().isEmpty()){
            end=Integer.valueOf(dennam.getText());
        }
        try {                                      
                // TODO add your handling code here:
                tb.setRowCount(0);
                if(begin > end){
                    jLabel4.setText("Thông tin không hợp lệ.\nVui lòng kiểm tra lại...");
                    jLabel4.setVisible(true);
                    return;
                }
                jLabel4.setVisible(false);
                PreparedStatement pr;
                ResultSet re;
                String select="SELECT NAM,sum(SLS),sum(SLKH),sum(SLC) FROM FUNC_TKNAM (?,?) GROUP BY NAM ORDER BY NAM";
                pr=SQL.getConnection().prepareStatement(select);
                try {
                    pr.setInt(1, begin);
                    pr.setInt(2,end);
                    re=pr.executeQuery();//thực hiện câu lệnh có trả về
                    if(re.isBeforeFirst()){
                        // vector giá trị ko biết đc
                        Vector a;
                        int i=1;
                        //chèn dòng đếm
                        while(re.next()){
                            a=new Vector();
                            a.add(i);
                            a.add(re.getString(1));
                            a.add(re.getString(2));
                            a.add(re.getString(3));
                            a.add(re.getString(4));
                            tb.addRow(a);
                            i++;
                        }
                    }
                    TK.setModel(tb);
                }
                catch (SQLException ex) {
                    Logger.getLogger(TGTV.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
            } 
            catch (SQLException ex) {
                Logger.getLogger(TGTV.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void tunamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tunamKeyPressed
        // TODO add your handling code here:
        char chr=evt.getKeyChar();
        String nam=tunam.getText();
        int limit=nam.length();
        if(chr==65535 || chr==127 || chr==27 || chr==10){
            return;
        }
        if(chr==8){
            if((limit-1)<1 || (limit-1)==4){
                jLabel4.setVisible(false);
                return;
            }
        }
        if((limit+1)>4){
            jLabel4.setVisible(true);
            jLabel4.setText("Bạn nhập sai.\nVui lòng kiểm tra lại...");
            return;
        }
        if(evt.getKeyChar()<'0' || evt.getKeyChar()>'9'){
            jLabel4.setText("Bạn nhập sai.\nVui lòng kiểm tra lại...");
            jLabel4.setVisible(true);
            return;
        }
        jLabel4.setVisible(false);
    }//GEN-LAST:event_tunamKeyPressed

    private void dennamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dennamKeyPressed
        // TODO add your handling code here:
         char chr=evt.getKeyChar();
        String nam=dennam.getText();
        int limit=nam.length();
        if(chr==65535 || chr==127 || chr==27 || chr==10){ //bỏ qua cấc ký tự đặt biệt
            return;
        }  
        if(chr==8){ // xoa ký tự 
            if((limit-1)<1 || (limit-1)==4){ // nếu <1 hoặt ==4 thì sai trả về
                jLabel4.setVisible(false);
                return;
            }
        }
        if((limit+1)>4){ // nếu >4 thì xuất
            jLabel4.setVisible(true);
            jLabel4.setText("Bạn nhập sai.\nVui lòng kiểm tra lại...");
            return;
        }
        if(evt.getKeyChar()<'0' || evt.getKeyChar()>'9'){
            jLabel4.setText("Bạn nhập sai.\nVui lòng kiểm tra lại...");
            jLabel4.setVisible(true);
            return;
        }
        jLabel4.setVisible(false);                           
    }//GEN-LAST:event_dennamKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TK;
    private javax.swing.JTextField dennam;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tunam;
    // End of variables declaration//GEN-END:variables

}
