/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caygiapha;

import java.sql.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADT
 */
public class XTT extends javax.swing.JInternalFrame {
    private String[] head={"STT","Thành tích","Số lượng"};
    private DefaultTableModel tb;
    private String[] data;
    /**
     * Creates new form XTT_1
     */
    public XTT() {
        initComponents();
        tb= (DefaultTableModel) dsTT.getModel();
        if(Bridge.isOpen()){
            String []data=Bridge.getData();
            jtxTenOrMa.setText(data[0]);
            jtxTenOrMa.setEditable(false);
            Search();
        }
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jThongBao = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTenOrMa = new javax.swing.JLabel();
        jtxTenOrMa = new javax.swing.JTextField();
        But_Tim = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dsTT = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        But_ADDTT = new javax.swing.JButton();

        jThongBao.setMinimumSize(new java.awt.Dimension(400, 126));
        jThongBao.setResizable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hãy đảm bảo bạn nhập dữ liệu hợp lệ...");

        jButton3.setText("Đồng ý");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jThongBaoLayout = new javax.swing.GroupLayout(jThongBao.getContentPane());
        jThongBao.getContentPane().setLayout(jThongBaoLayout);
        jThongBaoLayout.setHorizontalGroup(
            jThongBaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jThongBaoLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jThongBaoLayout.setVerticalGroup(
            jThongBaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jThongBaoLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setClosable(true);
        setTitle("Xem Thành Tích");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("XEM CÁC THÀNH TÍCH CỦA THÀNH VIÊN");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTenOrMa.setText("Mã thành viên");

        But_Tim.setText("Tìm");
        But_Tim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                But_TimMouseClicked(evt);
            }
        });

        dsTT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Thành tích", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(dsTT);
        if (dsTT.getColumnModel().getColumnCount() > 0) {
            dsTT.getColumnModel().getColumn(0).setMinWidth(20);
            dsTT.getColumnModel().getColumn(0).setPreferredWidth(40);
            dsTT.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        jButton2.setText("Đóng");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        But_ADDTT.setText("Thêm thành tích");
        But_ADDTT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                But_ADDTTMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(But_Tim))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jTenOrMa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxTenOrMa, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(But_ADDTT, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTenOrMa)
                    .addComponent(jtxTenOrMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(But_Tim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(But_ADDTT))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    private void Search(){
        String cmd = "select LTT,[Số lượng]=count(LTT)";
        try {
                jThongBao.setVisible(false);
                PreparedStatement pre;
                ResultSet res;
                cmd+=" from TT where ID like ? group by LTT";
                pre=SQL.getConnection().prepareStatement(cmd);
                pre.setString(1, jtxTenOrMa.getText());
                res=pre.executeQuery(); 
                if(res.isBeforeFirst()==true){
                    tb.setRowCount(0);
                    int i=1;
                    Vector data;
                    while(res.next()){
                        data=new Vector();
                        data.add(i);
                        data.add(res.getString(1));
                        data.add(res.getString(2));
                        tb.addRow(data);
                        i++;
                    }
//                    dsTT.setModel(tb); 
                }
//                else {
//                    jLabel2.setText("Không tìm thấy thông tin...");
//                    jThongBao.setVisible(true);
//                    return;
//                }
        } catch (SQLException ex) {
                    jLabel2.setText("Hãy đảm bảo bạn đã nhập thông tin hợp lệ...");
                    jThongBao.setVisible(true);
            }
    }
    private void But_TimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_But_TimMouseClicked
        // TODO add your handling code here:
        Search();
    }//GEN-LAST:event_But_TimMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        jThongBao.dispose();
    }//GEN-LAST:event_jButton3MouseClicked

    private void But_ADDTTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_But_ADDTTMouseClicked
        // TODO add your handling code here:
        if(jtxTenOrMa.getText().isEmpty()||jtxTenOrMa.getText().length()<7||jtxTenOrMa.getText().length()>8) {
            JOptionPane.showMessageDialog(this, "Mã thành viên không hợp lệ!","Lỗi",1);
            return;
        }
        data=new String[]{jtxTenOrMa.getText()};
        Bridge.setData(data);
        MAIN.a.getJDesktop().add(new ADD_TT());
    }//GEN-LAST:event_But_ADDTTMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton But_ADDTT;
    private javax.swing.JButton But_Tim;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable dsTT;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jTenOrMa;
    private javax.swing.JDialog jThongBao;
    private javax.swing.JTextField jtxTenOrMa;
    // End of variables declaration//GEN-END:variables
}
