/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caygiapha;

import java.awt.event.KeyEvent;
import java.rmi.server.ExportException;
import java.sql.*;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADT
 */
public class XTV extends javax.swing.JInternalFrame {
    private String[] data;
    private int soloi;
    /**
     * Creates new form XTV_1
     */

    

    public XTV() {
        initComponents();
        Select();
        setVisible(true);
        soloi=0;
    }
    void Select (){
        try {
            DefaultTableModel tb= (DefaultTableModel) jTable1.getModel();
            Statement sta=SQL.getConnection().createStatement();
            ResultSet res;
            String cmd="select * from TCTVien() where hoten like N'"+HVT_ThanhVien.getText()+"%' ";
            
            if(ngaySinh.getSelectedIndex()!=0){
                cmd+=" and day(ngsinh)="+ngaySinh.getSelectedItem();
            }
            if(thangSinh.getSelectedIndex()!=0){
                cmd+=" and month(ngsinh)="+thangSinh.getSelectedItem();
            }
            if(!namSinh.getText().isEmpty()){
                cmd+=" and year(ngsinh)="+Integer.valueOf(namSinh.getText());
            }
            
            cmd+=" group by matv,hoten,ngsinh,doi_,CM order by matv";
            res=sta.executeQuery(cmd);
            int i=0;
            tb.setRowCount(0);
//            if(res.isBeforeFirst()==true){
                while(res.next()){
                    Object[] Odata=new Object[] {res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5)};
                    tb.addRow(Odata);
                }
        } catch (SQLException ex) {
            Logger.getLogger(XTV.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
 //   private void exit(){
 //       this.dispose();
 //   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        HVT_ThanhVien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ngaySinh = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        thangSinh = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        namSinh = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        But_XTT = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        TVkhonghople = new javax.swing.JLabel();
        But_XGKT = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        But_ADD_TV = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Xem Thông Tin Thành Viên");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("XEM THÔNG TIN THÀNH VIÊN");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("THÔNG TIN THÀNH VIÊN");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Họ tên", "Ngày sinh", "Đời", "Cha/mẹ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setText("Họ tên");

        HVT_ThanhVien.setBackground(new java.awt.Color(240, 240, 240));
        HVT_ThanhVien.setFocusCycleRoot(true);
        HVT_ThanhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HVT_ThanhVienActionPerformed(evt);
            }
        });
        HVT_ThanhVien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                HVT_ThanhVienKeyPressed(evt);
            }
        });

        jLabel3.setText("Ngày");
        jLabel3.setMaximumSize(new java.awt.Dimension(30, 14));
        jLabel3.setMinimumSize(new java.awt.Dimension(30, 14));
        jLabel3.setPreferredSize(new java.awt.Dimension(30, 14));

        ngaySinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn...", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));
        ngaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngaySinhActionPerformed(evt);
            }
        });
        ngaySinh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ngaySinhKeyPressed(evt);
            }
        });

        jLabel4.setText("Tháng");

        thangSinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn...", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        thangSinh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                thangSinhKeyPressed(evt);
            }
        });

        jLabel5.setText("Năm");

        namSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namSinhActionPerformed(evt);
            }
        });
        namSinh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                namSinhKeyPressed(evt);
            }
        });

        jButton2.setText("Tìm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });

        But_XTT.setText("Xem thành tích");
        But_XTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                But_XTTActionPerformed(evt);
            }
        });

        jLabel6.setText("Ngày sinh:");

        TVkhonghople.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TVkhonghople.setText("Tên thành viên không hợp lệ");

        But_XGKT.setText("Xem giấy tử");
        But_XGKT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                But_XGKTMouseClicked(evt);
            }
        });

        jButton4.setText("Sửa quan hệ");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        But_ADD_TV.setText("Thêm thành viên");
        But_ADD_TV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                But_ADD_TVMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HVT_ThanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TVkhonghople, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(But_XTT)
                        .addGap(18, 18, 18)
                        .addComponent(But_XGKT)
                        .addGap(18, 18, 18)
                        .addComponent(But_ADD_TV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(thangSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(193, 193, 193)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(HVT_ThanhVien, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TVkhonghople, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(thangSinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(namSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel6)
                    .addComponent(ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 28, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(But_XTT)
                    .addComponent(But_XGKT)
                    .addComponent(jButton4)
                    .addComponent(But_ADD_TV))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Error(){
        JOptionPane.showMessageDialog(this, "Vui lòng chọn thành viên","Lỗi",1);
    }
    /*
    private void HVT_ThanhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HVT_ThanhVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HVT_ThanhVienActionPerformed
*/
    private void ngaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ngaySinhActionPerformed

    private void namSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namSinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namSinhActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Select();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void But_XTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_But_XTTActionPerformed
        // TODO add your handling code here:
        try {
            String a=jTable1.getValueAt(jTable1.getSelectedRow(),0).toString();
//            System.out.println(a+"  "+b+" "+c);
            data=new String[]{a};
            Bridge.setData(data);
            MAIN.a.getJDesktop().add(new XTT());
        } catch (Exception e) {
            Error();
        }
    }//GEN-LAST:event_But_XTTActionPerformed

    private void HVT_ThanhVienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HVT_ThanhVienKeyPressed
        // TODO add your handling code here:
        int n=evt.getKeyChar();
        if(n==KeyEvent.VK_ENTER){
            Select();
            return;
        }
        if(n<'0'||n>'9'){
            if(soloi!=0)
            soloi--;
            return;
        }
        if((n<8&&n>127)&&(n!=27||n!=9||n!=20||n!=16||n!=17||n!=18||n!=32||n!=37||n!=38||n!=39||n!=40)){
                TVkhonghople.setVisible(true);
                soloi++;
                return;
        }
        n=HVT_ThanhVien.getText().charAt(HVT_ThanhVien.getText().length()-1);
        if(soloi==0){
            TVkhonghople.setVisible(false);
        }
    }//GEN-LAST:event_HVT_ThanhVienKeyPressed

    private void ngaySinhKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ngaySinhKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==KeyEvent.VK_ENTER)
            Select();
    }//GEN-LAST:event_ngaySinhKeyPressed

    private void thangSinhKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_thangSinhKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==KeyEvent.VK_ENTER)
            Select();
    }//GEN-LAST:event_thangSinhKeyPressed

    private void namSinhKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_namSinhKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==KeyEvent.VK_ENTER)
            Select();
    }//GEN-LAST:event_namSinhKeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==KeyEvent.VK_ENTER)
            Select();
    }//GEN-LAST:event_jButton2KeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:

        if(evt.getKeyChar()==KeyEvent.VK_ESCAPE)
            this.dispose();
    }//GEN-LAST:event_formKeyPressed

    private void But_XGKTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_But_XGKTMouseClicked
        // TODO add your handling code here:
        
        try {
            String a=jTable1.getValueAt(jTable1.getSelectedRow(),0).toString();
            data=new String[]{a};
            Bridge.setData(data);
            MAIN.a.getJDesktop().add(new XGKT());
        } catch (Exception e) {
            Error();
        }
        
    }//GEN-LAST:event_But_XGKTMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        try {
            String a = (String) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
            data=new String[]{a};
            Bridge.setData(data);
            MAIN.a.getJDesktop().add(new SQH());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Hãy chọn một thành viên!","Lỗi",1);
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void But_ADD_TVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_But_ADD_TVMouseClicked
        // TODO add your handling code here:
        try {
            String a = (String) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
            data=new String[]{a};
            Bridge.setData(data);
            MAIN.a.getJDesktop().add(new ADD_TV());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Hãy chọn một thành viên!","Lỗi",1);
        }
    }//GEN-LAST:event_But_ADD_TVMouseClicked


    public void HVT_ThanhVienActionPerformed(java.awt.event.ActionEvent evt) {
                
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton But_ADD_TV;
    private javax.swing.JButton But_XGKT;
    private javax.swing.JButton But_XTT;
    private javax.swing.JTextField HVT_ThanhVien;
    private javax.swing.JLabel TVkhonghople;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField namSinh;
    private javax.swing.JComboBox<String> ngaySinh;
    private javax.swing.JComboBox<String> thangSinh;
    // End of variables declaration//GEN-END:variables
}
